quarkus:
  swagger-ui:
    theme: material
    always-include: true

  live-reload:
    instrumentation: true
  application:
    name: free-image-upload
  http:
    port: ${PORT:6010}
    cors:
      origins: http://localhost:3000
      ~: true
  smallrye-openapi:
    path: /swagger
  log:
    level: ALL
  container-image:
    build: true
    group: ${quarkus.application.name}
    name: upload
    tag: latest
imagekit:
  url: ${IMAGEKIT_URL}
  private: ${IMAGEKIT_PRIVATE}
  public: ${IMAGEKIT_PUBLIC}
  api: ${IMAGEKIT_API_PRIVATE}
